apiVersion: v1
kind: Secret
metadata:
  name: iam-db-secret
  namespace: onprem-iam
type: Opaque
stringData:
  DB_HOST: "192.168.1.151"
  DB_PORT: "5432"
  DB_NAME: "iam_db"
  DB_USER: "iam_app_user"
  DB_PASSWORD: "password123"

