apiVersion: v1
kind: Secret
metadata:
  name: "{{ finance_engine_db_secret_name }}"
  namespace: "{{ apps_namespace }}"
type: Opaque
stringData:
  username: "{{ finance_engine_db_user }}"
  password: "{{ finance_engine_db_password }}"

