apiVersion: v1
kind: Service

metadata:
  name: ingest-service
  namespace: "{{ apps_namespace }}"
  labels:
    app: ingest-service

spec:
  type: ClusterIP

  selector:
    app: ingest-service

  ports:
    - name: http
      port: {{ csv_ingest_port | int }}
      targetPort: {{ csv_ingest_port | int }}
      protocol: TCP

