{
 "title": "하이브리드 플랫폼 관측 대시보드 (Baseline)",
 "tags": [
  "baseline",
  "gitops",
  "hybrid",
  "k3s"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_container_status_ready,namespace)"
    }
   },
   { "name": "job", "label": "job", "query": { "query": "label_values(up,job)" } }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "모니터링 시스템 정상 동작 여부",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg by (app) (\r\n  label_replace(\r\n    kube_pod_container_status_ready{\r\n      namespace=~\"$namespace\",\r\n      pod=~\"(alertmanager|grafana|loki|prometheus).*\"\r\n    } == 1,\r\n    \"app\",\r\n    \"$1\",\r\n    \"pod\",\r\n    \"(alertmanager|grafana|loki|prometheus).*\"\r\n  )\r\n)\r\n",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "전체 메트릭 수집 지연 시간",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(scrape_duration_seconds)" }
   ]
  },
  {
   "title": "전체 메트릭 수집 실패 대상 수",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(up == 0) or vector(0)" }
   ]
  },
  {
   "title": "최근 10분간 재시작 발생 여부",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(max(sum by (namespace, pod) (increase(kube_pod_container_status_restarts_total[10m])) ) > 0) OR vector(0)"
    }
   ]
  },
  {
   "title": "재시작 목록 (최근 10분)",
   "type": "table",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (namespace, pod) (increase(kube_pod_container_status_restarts_total[10m]))"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Postgres Exporter Up ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(up{job=~\".*postgres.*\"}) or vector(0)",
     "legendFormat": "Exporter Up"
    }
   ]
  },
  {
   "title": "Postgres DB Up ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(pg_up) or vector(0)" }
   ]
  },
  {
   "title": "Postgres 메트릭 수집 지연 시간",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(scrape_duration_seconds{job=~\".*postgres.*\"})"
    }
   ]
  },
  {
   "title": "TPS (Transactions Per Second) ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_xact_commit[10m]))\r\n+\r\nsum(rate(pg_stat_database_xact_rollback[10m]))\r\n",
     "legendFormat": "tps"
    }
   ]
  },
  {
   "title": "Commit / Rollback",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_xact_commit[5m]))",
     "legendFormat": "commit"
    },
    {
     "expr": "sum(rate(pg_stat_database_xact_rollback[5m]))",
     "legendFormat": "rollback"
    }
   ]
  },
  {
   "title": "Idle Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{state=\"idle\"})",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "Active Connections ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 20 },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{state=\"active\"})",
     "legendFormat": "active"
    }
   ]
  },
  {
   "title": "Connection Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(100 * sum(pg_stat_activity_count) / max(pg_settings_max_connections)) or vector(0)"
    }
   ]
  },
  {
   "title": "Deadlocks/sec",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_deadlocks[5m])) or vector(0)"
    }
   ]
  },
  {
   "title": "Deadlocks by Database",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 4, "y": 28 },
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_stat_database_deadlocks[5m]))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Lock Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 13, "y": 28 },
   "targets": [
    { "expr": "sum(pg_locks_count)", "legendFormat": "locks" }
   ]
  },
  {
   "title": "DB 평균 Cache Hit Ratio",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\nsum(rate(pg_stat_database_blks_hit[5m]))\r\n/\r\n(\r\n  sum(rate(pg_stat_database_blks_hit[5m]))\r\n  +\r\n  sum(rate(pg_stat_database_blks_read[5m]))\r\n)\r\n\r\n"
    }
   ]
  },
  {
   "title": "Disk Read / Write (IOPS)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 4, "y": 36 },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_blks_read[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(pg_stat_database_blks_written[5m]))",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Dead Tuples (Time series)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 13, "y": 36 },
   "targets": [
    { "expr": "pg_stat_user_tables_n_dead_tup", "legendFormat": "{{relname}}" }
   ]
  }
 ]
}