apiVersion: v1
kind: Secret
metadata:
  name: postgres-exporter-secret
  namespace: onprem-monitoring
type: Opaque
stringData:
  # PostgreSQL Exporter가 사용하는 표준 환경변수
  # DSN 형식: postgresql://user:password@host:port/db?sslmode=disable
  DATA_SOURCE_NAME: >-
    postgresql://{{ postgres_exporter_db_user }}:{{ postgres_exporter_db_password }}
    @{{ postgres_exporter_db_host }}:{{ postgres_exporter_db_port }}/{{ postgres_exporter_db_name }}
    ?sslmode={{ postgres_exporter_sslmode }}


