apiVersion: v1
kind: Secret
metadata:
  name: audit-common-secret
  namespace: onprem-audit
type: Opaque
stringData:
  DB_HOST: "192.168.1.151"
  DB_PORT: "5432"
  DB_NAME: "audit_db"
  DB_USER: "audit_reader"
  DB_PASSWORD: "password123"
