apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: "{{ nfs_pvc_name }}"               # 예: csv-ingest-pvc
  namespace: "{{ nfs_pvc_namespace }}"     # 예: onprem-apps

spec:
  accessModes:
    - ReadWriteMany

  resources:
    requests:
      storage: "{{ nfs_storage_size }}"    # PV와 반드시 동일

  volumeName: "{{ nfs_pv_name }}"          # PV에 명시적 바인딩

