# =========================
# kube-prometheus-stack (alias: kps)
# =========================
kps:
  grafana:
    adminUser: admin
    adminPassword: "grafana1234!"

    service:
      type: ClusterIP

    persistence:
      enabled: true
      type: pvc
      storageClassName: gp3
      accessModes:
        - ReadWriteOnce
      size: 10Gi

    sidecar:
      datasources:
        enabled: true
        label: grafana_datasource
        labelValue: "1"          # ✅ 추가: CM 라벨 값("1")과 매칭
        defaultDatasourceEnabled: false   # ✅ 추가 (kps가 만드는 기본 datasource CM 끔)
      dashboards:
        enabled: true
        label: grafana_dashboard
        labelValue: "1"

  prometheus:
    service:
      type: ClusterIP

    prometheusSpec:
      retention: 15d
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: gp3
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 50Gi

  alertmanager:
    service:
      type: ClusterIP

    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: gp3
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi


# =========================
# Loki (single binary)
# =========================
loki:
  deploymentMode: SingleBinary

  loki:
    auth_enabled: false

    commonConfig:
      replication_factor: 1

    schemaConfig:
      configs:
        - from: "2024-01-01"
          store: boltdb-shipper
          object_store: filesystem
          schema: v13
          index:
            prefix: loki_index_
            period: 24h

    storage:
      type: filesystem

    ruler:
      enable_api: false

  singleBinary:
    replicas: 1
    persistence:
      enabled: true
      size: 50Gi
      storageClass: gp3
      accessModes:
        - ReadWriteOnce

  read:
    enabled: false
  write:
    enabled: false
  backend:
    enabled: false

  lokiCanary:
    enabled: false
  gateway:
    enabled: false

  monitoring:
    selfMonitoring:
      enabled: false

  test:
    enabled: false
