apiVersion: v1
kind: Secret
metadata:
  name: audit-common-secret
  namespace: onprem-audit
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: audit_reader
  SPRING_DATASOURCE_PASSWORD: password123

