apiVersion: v1
kind: Namespace
metadata:
  name: onprem-iam
---
apiVersion: v1
kind: Namespace
metadata:
  name: onprem-apps
---
apiVersion: v1
kind: Namespace
metadata:
  name: onprem-audit
---
apiVersion: v1
kind: Namespace
metadata:
  name: onprem-monitoring

