variable "domain_name" {
  type        = string
  description = "Apex domain (e.g., rockyvicky.com)"
}

variable "hosted_zone_id" {
  type        = string
  description = "Route53 Hosted Zone ID for domain_name (e.g., Z026...)"
}

variable "create_wildcard" {
  type        = bool
  default     = true
  description = "If true, include *.domain_name in SAN"
}

variable "additional_sans" {
  type        = list(string)
  default     = []
  description = "Additional SANs, if you want (e.g., ['api.rockyvicky.com','admin.rockyvicky.com']). Usually wildcard covers these."
}

variable "tags" {
  type        = map(string)
  default     = {}
}

variable "certificate_name" {
  type        = string
  default     = ""
  description = "Optional Name tag. If empty, autogenerated."
}
