---------------------------------------------
    # Database Servers
    # ------------------------------------------------------
    db_servers:
      hosts:
        onprem-master:
          ansible_host: 3.26.144.20
          ansible_user: ec2-user
          ansible_ssh_private_key_file: /root/ansible-rocky9/Project/per11.pem
          ansible_connection: ssh

    # ------------------------------------------------------
    # Kubernetes Control Plane
    # ------------------------------------------------------
    k8s_control_plane:
      hosts:
        onprem-master:
          ansible_host: 3.26.144.20
          ansible_user: ec2-user
          ansible_ssh_private_key_file: /root/ansible-rocky9/Project/per11.pem
          ansible_connection: ssh

    # ---------------------------------------
