apiVersion: v1
kind: Secret
metadata:
  name: audit-relay-secret
  namespace: onprem-audit
type: Opaque
stringData:
  OPENSEARCH_URL: http://opensearch.onprem-monitoring.svc.cluster.local:9200
  OPENSEARCH_USERNAME: audit_relay
  OPENSEARCH_PASSWORD: password123

