apiVersion: v1
kind: Secret
metadata:
  name: postgres-exporter-secret
  namespace: onprem-monitoring
type: Opaque

stringData:
  # PostgreSQL Exporter 표준 환경변수
  # DSN 형식: postgresql://user:password@host:port/db?sslmode=disable
  DATA_SOURCE_NAME: "postgresql://postgres:password123@192.168.1.151:5432/postgres?sslmode=disable"

