spring:
  application:
    name: audit-writer

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 600000

  sql:
    init:
      mode: never

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.jdbc.core.JdbcTemplate: DEBUG

