- name: Deploy audit-relay Deployment
  kubernetes.core.k8s:
    state: present
    namespace: "{{ apps_namespace }}"
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: audit-relay
        labels:
          app: audit-relay
      spec:
        replicas: "{{ audit_relay_replicas}}"   # ✅ FIX
        strategy:
          type: Recreate
        selector:
          matchLabels:
            app: audit-relay
        template:
          metadata:
            labels:
              app: audit-relay
          spec:
            serviceAccountName: audit-relay
            containers:
              - name: audit-relay
                image: "{{ audit_relay_image }}"
                imagePullPolicy: IfNotPresent

                envFrom:
                  - secretRef:
                      name: audit-relay-secret

                env:
                  - name: OS_HOST
                    value: "{{ audit_os_host }}"
                  - name: OS_PORT
                    value: "{{ audit_os_port | string }}"
                  - name: OS_INDEX
                    value: "{{ audit_os_index }}"
                  - name: BATCH_SIZE
                    value: "{{ audit_relay_batch_size | string }}"
                  - name: POLL_INTERVAL
                    value: "{{ audit_relay_poll_interval | string }}"

                resources:
                  requests:
                    cpu: "{{ audit_relay_cpu_request }}"
                    memory: "{{ audit_relay_memory_request }}"
                  limits:
                    cpu: "{{ audit_relay_cpu_limit }}"
                    memory: "{{ audit_relay_memory_limit }}"

