apiVersion: v1
kind: Secret
metadata:
  name: "{{ audit_relay_db_secret_name }}"
  namespace: "{{ apps_namespace }}"
type: Opaque
stringData:
  username: "{{ audit_relay_db_user }}"
  password: "{{ audit_relay_db_password }}"

