variable "domain_name" {
  type        = string
  description = "Apex domain (e.g., rockyvicky.com)"
}

variable "create_certificate" {
  type        = bool
  default     = true
  description = "true: create ACM cert + DNS validation records / false: reference existing certificate"
}

variable "existing_certificate_arn" {
  type        = string
  default     = ""
  description = "If create_certificate=false and you want to pin a specific cert, set its ARN."
}

variable "hosted_zone_id" {
  type        = string
  default     = ""
  description = "Route53 Hosted Zone ID (required when create_certificate=true)"
}

variable "create_wildcard" {
  type        = bool
  default     = true
  description = "If true, include *.domain_name in SAN"
}

variable "additional_sans" {
  type        = list(string)
  default     = []
  description = "Additional SANs if needed. Wildcard usually covers subdomains."
}

variable "tags" {
  type    = map(string)
  default = {}
}

variable "certificate_name" {
  type        = string
  default     = ""
  description = "Optional Name tag. If empty, autogenerated."
}
