apiVersion: v1
kind: Secret
metadata:
  name: audit-query-api-db-secret
type: Opaque

stringData:
  DB_HOST: "{{ db_host }}"
  DB_PORT: "{{ db_port | string }}"
  DB_NAME: "{{ db_name }}"
  DB_USER: "{{ audit_query_api_db_user }}"
  DB_PASSWORD: "{{ audit_query_api_db_password }}"

