apiVersion: v1
kind: Service

metadata:
  name: audit-query-api
  namespace: "{{ audit_namespace }}"

spec:
  type: ClusterIP

  selector:
    app: audit-query-api

  ports:
    - name: http
      port: 80
      targetPort: {{ audit_query_api_port | int }}
      protocol: TCP

