apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csv-ingest-pvc
  namespace: onprem-apps

spec:
  accessModes:
    - ReadWriteMany

  resources:
    requests:
      storage: 10Gi

  volumeName: csv-ingest-pv
  storageClassName: ""

